/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author hp
 */
public class calculator extends javax.swing.JFrame implements Calculations {

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PercentageButton = new javax.swing.JButton();
        SqrtButton = new javax.swing.JButton();
        x2Button = new javax.swing.JButton();
        OneByXButton = new javax.swing.JButton();
        CEButton = new javax.swing.JButton();
        CButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        DivitionButton = new javax.swing.JButton();
        no7Button = new javax.swing.JButton();
        no8Button = new javax.swing.JButton();
        no9Button = new javax.swing.JButton();
        MultiplicationButton = new javax.swing.JButton();
        no6Button = new javax.swing.JButton();
        no5Button = new javax.swing.JButton();
        no4Button = new javax.swing.JButton();
        SubtractionButton = new javax.swing.JButton();
        AdditionButton = new javax.swing.JButton();
        no3Button = new javax.swing.JButton();
        no2Button = new javax.swing.JButton();
        no1Button = new javax.swing.JButton();
        EqualsButton = new javax.swing.JButton();
        PlusOrMinusButton = new javax.swing.JButton();
        DecimalPointButton = new javax.swing.JButton();
        no0Button = new javax.swing.JButton();
        CalInput = new javax.swing.JTextField();
        CalScreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PercentageButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PercentageButton.setText("%");
        PercentageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentageButtonActionPerformed(evt);
            }
        });

        SqrtButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SqrtButton.setText("Sqrt");
        SqrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SqrtButtonActionPerformed(evt);
            }
        });

        x2Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        x2Button.setText("X2");
        x2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2ButtonActionPerformed(evt);
            }
        });

        OneByXButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        OneByXButton.setText("1/x");
        OneByXButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneByXButtonActionPerformed(evt);
            }
        });

        CEButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CEButton.setText("CE");
        CEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEButtonActionPerformed(evt);
            }
        });

        CButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CButton.setText("C");
        CButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BackButton.setText("<--");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        DivitionButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DivitionButton.setText("/");
        DivitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivitionButtonActionPerformed(evt);
            }
        });

        no7Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no7Button.setText("7");
        no7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no7ButtonActionPerformed(evt);
            }
        });

        no8Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no8Button.setText("8");
        no8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no8ButtonActionPerformed(evt);
            }
        });

        no9Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no9Button.setText("9");
        no9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no9ButtonActionPerformed(evt);
            }
        });

        MultiplicationButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MultiplicationButton.setText("*");
        MultiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicationButtonActionPerformed(evt);
            }
        });

        no6Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no6Button.setText("6");
        no6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no6ButtonActionPerformed(evt);
            }
        });

        no5Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no5Button.setText("5");
        no5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no5ButtonActionPerformed(evt);
            }
        });

        no4Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no4Button.setText("4");
        no4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no4ButtonActionPerformed(evt);
            }
        });

        SubtractionButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SubtractionButton.setText("-");
        SubtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractionButtonActionPerformed(evt);
            }
        });

        AdditionButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdditionButton.setText("+");
        AdditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionButtonActionPerformed(evt);
            }
        });

        no3Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no3Button.setText("3");
        no3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no3ButtonActionPerformed(evt);
            }
        });

        no2Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no2Button.setText("2");
        no2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no2ButtonActionPerformed(evt);
            }
        });

        no1Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no1Button.setText("1");
        no1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ButtonActionPerformed(evt);
            }
        });

        EqualsButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EqualsButton.setText("=");
        EqualsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualsButtonActionPerformed(evt);
            }
        });

        PlusOrMinusButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PlusOrMinusButton.setText("+-");
        PlusOrMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusOrMinusButtonActionPerformed(evt);
            }
        });

        DecimalPointButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DecimalPointButton.setText(".");
        DecimalPointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecimalPointButtonActionPerformed(evt);
            }
        });

        no0Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no0Button.setText("0");
        no0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no0ButtonActionPerformed(evt);
            }
        });

        CalInput.setEditable(false);
        CalInput.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CalInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CalInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CalScreen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CalScreen.setForeground(new java.awt.Color(0, 0, 153));
        CalScreen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PercentageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(SqrtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(x2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(OneByXButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(CButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(DivitionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(no7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(no8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(no9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(MultiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(no4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(no5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(no6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(SubtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(no1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(no2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(no3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(AdditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PlusOrMinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(no0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(DecimalPointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CalInput)
                    .addComponent(CalScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(CalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CalScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PercentageButton)
                    .addComponent(SqrtButton)
                    .addComponent(x2Button)
                    .addComponent(OneByXButton))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEButton)
                    .addComponent(CButton)
                    .addComponent(BackButton)
                    .addComponent(DivitionButton))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no7Button)
                    .addComponent(no8Button)
                    .addComponent(no9Button)
                    .addComponent(MultiplicationButton))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no4Button)
                    .addComponent(no5Button)
                    .addComponent(no6Button)
                    .addComponent(SubtractionButton))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no1Button)
                    .addComponent(no2Button)
                    .addComponent(no3Button)
                    .addComponent(AdditionButton))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlusOrMinusButton)
                    .addComponent(no0Button)
                    .addComponent(DecimalPointButton)
                    .addComponent(EqualsButton))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PercentageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PercentageButtonActionPerformed
        // TODO add your handling code here:
        if ((CalInput.getText().length() > 0)&&(CalScreen.getText().length() > 0)) {
            toBeCalculatedValue = Double.parseDouble(CalInput.getText());
            percentage(Double.parseDouble(CalScreen.getText().split(" ")[0]),toBeCalculatedValue);
        }
        
            
    }//GEN-LAST:event_PercentageButtonActionPerformed

    private void SqrtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SqrtButtonActionPerformed
        // TODO add your handling code here:
        toBeCalculatedValue = Double.parseDouble(CalInput.getText());
        sqrRoot(toBeCalculatedValue);
    }//GEN-LAST:event_SqrtButtonActionPerformed

    private void x2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2ButtonActionPerformed
        // TODO add your handling code here:
        if(CalInput.getText().length()>0){
            toBeCalculatedValue = Double.parseDouble(CalInput.getText());
            square(toBeCalculatedValue);
        }
    }//GEN-LAST:event_x2ButtonActionPerformed

    private void OneByXButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneByXButtonActionPerformed
        // TODO add your handling code here:
         if(CalInput.getText().length()>0){
            toBeCalculatedValue = Double.parseDouble(CalInput.getText());
            oneByX(toBeCalculatedValue);
        }
    }//GEN-LAST:event_OneByXButtonActionPerformed

    private void CEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEButtonActionPerformed
        // TODO add your handling code here:
         CalInput.setText("");
         isDecimal = false;
         
    }//GEN-LAST:event_CEButtonActionPerformed

    private void CButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CButtonActionPerformed
        // TODO add your handling code here:
        CalInput.setText("");
        CalScreen.setText("");
        isDecimal = false;

    }//GEN-LAST:event_CButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        String value = CalInput.getText();
        int length = value.length();

        if (length > 0) {
            StringBuilder builder = new StringBuilder(value);
            builder.deleteCharAt(length - 1);
            CalInput.setText(builder.toString());
        }
    }//GEN-LAST:event_BackButtonActionPerformed

    private void DivitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivitionButtonActionPerformed
        // TODO add your handling code here:
        sign = "/";
        if (CalInput.getText().length() > 0) {

            storeToBeCalculatedValue(sign);
        }
        isDecimal = false;
    }//GEN-LAST:event_DivitionButtonActionPerformed

    private void no7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no7ButtonActionPerformed
        CalInput.setText(CalInput.getText() + "7");
    }//GEN-LAST:event_no7ButtonActionPerformed

    private void no8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no8ButtonActionPerformed
        CalInput.setText(CalInput.getText() + "8");
    }//GEN-LAST:event_no8ButtonActionPerformed

    private void no9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no9ButtonActionPerformed
        CalInput.setText(CalInput.getText() + "9");
    }//GEN-LAST:event_no9ButtonActionPerformed

    private void MultiplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicationButtonActionPerformed
        // TODO add your handling code here:
        sign = "*";
        if (CalInput.getText().length() > 0) {
            storeToBeCalculatedValue(sign);
        }
        isDecimal = false;
    }//GEN-LAST:event_MultiplicationButtonActionPerformed

    private void no6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no6ButtonActionPerformed
        CalInput.setText(CalInput.getText() + "6");
    }//GEN-LAST:event_no6ButtonActionPerformed

    private void no5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no5ButtonActionPerformed
        CalInput.setText(CalInput.getText() + "5");
    }//GEN-LAST:event_no5ButtonActionPerformed

    private void no4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no4ButtonActionPerformed
        CalInput.setText(CalInput.getText() + "4");
    }//GEN-LAST:event_no4ButtonActionPerformed

    private void SubtractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractionButtonActionPerformed
        // TODO add your handling code here:
        sign = "-";
        if (CalInput.getText().length() > 0) {
            storeToBeCalculatedValue(sign);
        }
        isDecimal = false;
    }//GEN-LAST:event_SubtractionButtonActionPerformed

    private void AdditionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditionButtonActionPerformed
        // TODO add your handling code here:
        sign = "+";
        if (CalInput.getText().length() > 0) {
            storeToBeCalculatedValue(sign);
        }
        isDecimal = false;
    }//GEN-LAST:event_AdditionButtonActionPerformed

    private void no3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no3ButtonActionPerformed
        CalInput.setText(CalInput.getText() + "3");
    }//GEN-LAST:event_no3ButtonActionPerformed

    private void no2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no2ButtonActionPerformed
        CalInput.setText(CalInput.getText() + "2");

    }//GEN-LAST:event_no2ButtonActionPerformed

    private void no1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no1ButtonActionPerformed
        CalInput.setText(CalInput.getText() + "1");
    }//GEN-LAST:event_no1ButtonActionPerformed

    private void EqualsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualsButtonActionPerformed
        // TODO add your handling code here:
        if (CalInput.getText().length() > 0) {
            double b = Double.parseDouble(CalInput.getText());
            switch (sign) {
                case "+":
                    add(toBeCalculatedValue, b);
                    break;
                case "-":
                    substract(toBeCalculatedValue, b);
                    break;
                case "*":
                    multiply(toBeCalculatedValue, b);
                    break;
                case "/":
                    divide(toBeCalculatedValue, b);
                    break;
            }
        }
        isDecimal = false;
    }//GEN-LAST:event_EqualsButtonActionPerformed

    private void PlusOrMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusOrMinusButtonActionPerformed
        // TODO add your handling code here:
        String value = CalInput.getText();

        if (!value.contains("-")) {
            CalInput.setText("-" + value);
        } else {
            try {
                CalInput.setText(value.split("-")[1]);
            } catch (IndexOutOfBoundsException e) {
                CalInput.setText("");
            }
        }
    }//GEN-LAST:event_PlusOrMinusButtonActionPerformed

    private void DecimalPointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecimalPointButtonActionPerformed
        if (!isDecimal) {
            CalInput.setText(CalInput.getText() + ".");
            isDecimal = true;
        }
    }//GEN-LAST:event_DecimalPointButtonActionPerformed

    private void no0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no0ButtonActionPerformed
        CalInput.setText(CalInput.getText() + "0");
    }//GEN-LAST:event_no0ButtonActionPerformed

    @Override
    public void add(double a, double b) {
        setResults(a + b);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void substract(double a, double b) {
        setResults(a - b);

        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void multiply(double a, double b) {

        setResults(a * b);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void divide(double a, double b) {

        setResults(a / b);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setResults(double result) {
        CalInput.setText(Double.toString(result));
        CalScreen.setText(" ");
    }

    private void storeToBeCalculatedValue(String sign) {

        String value = CalInput.getText();
        toBeCalculatedValue = Double.parseDouble(value);
        CalScreen.setText(value + " " + sign);
        CalInput.setText(" ");

    }

    private void percentage(double a, double b) {

        switch (sign) {
            case "+":
                add(((a*b)/100),a);
                break;
            case "-":
                substract(a,((a*b)/100));
                break;
            case "*":
                multiply(((a*b)/100),a);
                break;
            case "/":
                divide(a,((a*b)/100));
                break;
        }
    }
    private void sqrRoot(double a){
        
       CalInput.setText(Double.toString(Math.sqrt(a)));
    }
    
    private void square(double a){
        CalInput.setText(Double.toString(Math.pow(a, 2)));
    }
    
    private void  oneByX(double a){
        CalInput.setText(Double.toString(1/a));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    //variable to handle decimal point
    private boolean isDecimal = false;
    private String sign;
    private double toBeCalculatedValue;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdditionButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CButton;
    private javax.swing.JButton CEButton;
    private javax.swing.JTextField CalInput;
    private javax.swing.JLabel CalScreen;
    private javax.swing.JButton DecimalPointButton;
    private javax.swing.JButton DivitionButton;
    private javax.swing.JButton EqualsButton;
    private javax.swing.JButton MultiplicationButton;
    private javax.swing.JButton OneByXButton;
    private javax.swing.JButton PercentageButton;
    private javax.swing.JButton PlusOrMinusButton;
    private javax.swing.JButton SqrtButton;
    private javax.swing.JButton SubtractionButton;
    private javax.swing.JButton no0Button;
    private javax.swing.JButton no1Button;
    private javax.swing.JButton no2Button;
    private javax.swing.JButton no3Button;
    private javax.swing.JButton no4Button;
    private javax.swing.JButton no5Button;
    private javax.swing.JButton no6Button;
    private javax.swing.JButton no7Button;
    private javax.swing.JButton no8Button;
    private javax.swing.JButton no9Button;
    private javax.swing.JButton x2Button;
    // End of variables declaration//GEN-END:variables
}
